name: Ejecucion de Pruebas de API REST

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Obtener codigo del repositorio
        uses: actions/checkout@v4

      - name: Ejecutar pruebas de API con Cypress
        uses: cypress-io/github-action@v6
        with:
          browser: chrome